--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Milchreisfan/LittleCore
build-by-default: true
branches:
- main
- PM4 #remove that if this branch does no longer exists
projects:
  LittleCore:
    path: ""
...
