--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Milchreisfan/LittleCore
build-by-default: true
branches:
- master
projects:
  LittleCore:
    version: 1.1.0
    description: Ein kleiner Core | A little core 
    icon: "lc.png"
    path: ""
...
