name: LittleCore
version: 1.9.2-PM4
api: 4.0.0
main: Milchreisfan\LittleCore\Main
authors:
  - Milchreisfan
  - supercrafter333
description: Core für PocketMine-MP | A Core for PocketMine-MP
website: "https://github.com/Milchreisfan"