name: LittleCore
version: 1.3.0
api: 3.0.0, 4.0.0
main: Milchreisfan\LittleCore\Main
author: Milchreisfan
description: Core für PocketMine-MP | A Core for PocketMine-MP
website: "https://github.com/Milchreisfan"